### ISSUE TITLE
Пожалуйста, помогите. Игра не запускается

### ISSUE THREAD

**Issue by Gilsson** [Krigoxar/Gorchakov_OSISP_prj_2024-#1]
При установке выводит сообщение, что название игры скоро изменится. Сама игра не запускается. Прошу исправить
![image](https://github.com/Krigoxar/NetSraner-space/assets/86572717/8f688acd-3766-419f-bd57-9b75a2b9cd10)

**Comment by Krigoxar** [comment]
Скорее всего ошибка возникла из-за того, что у вас слишком слабая система.
Возможные способы исправления вашей проблемы:
- Купите себе новый копутер.
- Арендуйте сервертайм в любом кластере.
- сдаться.

**Comment by Gilsson** [comment]
> * сдаться.

Помогло! Спасибо
